### ISSUE TITLE
在 Releases 中是否可以提供一个包含许可证在内的 zip 包

### ISSUE THREAD

**Issue by TakWolf** [scott0107000/BoutiqueBitmap9x9#1]
RT. 以保证分发的完整性，而不需要单独下载许可证。谢谢

**Comment by scott0107000** [comment]
你好！已新增 zip 压缩包，感谢提醒！

**Comment by TakWolf** [comment]
git tag name 目前还不符合习惯规范，目前是 `publish`，应该和版本号对应为 `1.5` 或者 `v1.5`

<img width="261" alt="image" src="https://github.com/scott0107000/BoutiqueBitmap9x9/assets/6064962/b8b8375d-346e-477d-8cb4-ed29b13307f7">

**Comment by scott0107000** [comment]
好的！我新增了一个新的 tag 来使用，我删除旧的会有任何影响吗？

**Comment by TakWolf** [comment]
不影响，只是你已创建的 release 会变成草稿
新的 release 需要重新上传资源

**Comment by scott0107000** [comment]
谢谢！我处理好了，想请问还有什么地方需要修改吗

**Comment by TakWolf** [comment]
目前很完美！！！
